Repository boostcampwm-2022/iOS08_Acha, pull requests merged in 2022-12, with the labels that each got.

#115 [인증] UserRepository, AuthService, KeychainService -- conflic 나고 빌드 오류 나서 다시 올립니다
  .gitattributes
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Data/DTO/CommentDTO.swift
  Acha/Acha/Data/DTO/CommunityDTO.swift
  Acha/Acha/Data/DTO/PostDTO.swift
  Acha/Acha/Data/DTO/UserDTO.swift
  Acha/Acha/Data/Repository/DefaultCommunityRepository.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Data/Repository/Protocol/UserRepository.swift
  Acha/Acha/Domain/Entity/Comment.swift
  Acha/Acha/Domain/Entity/Post.swift
  Acha/Acha/Domain/Entity/User.swift
  Acha/Acha/Presentation/TabBar/Community/Cell/CommunityCollectionViewCell.swift
  Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityViewController.swift
  Acha/Acha/Presentation/TabBar/Home/HomeView/ViewController/HomeViewController.swift
  Acha/Acha/Util/Enums/FirebaseRealtimeType.swift
  Acha/Acha/Util/Service/DefaultAuthService.swift
  Acha/Acha/Util/Service/DefaultKeychainService.swift
  Acha/Acha/Util/Service/Protocol/AuthService.swift
  Acha/Acha/Util/Service/Protocol/KeychainService.swift
Labels: bug, feature

#117 [MyPage] UI + 기능
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha.xcodeproj/xcshareddata/xcschemes/Acha.xcscheme
  Acha/Acha/App/Coordinator/AppCoordinator.swift
  Acha/Acha/Data/BadgeDTO.swift
  Acha/Acha/Data/DTO/BadgeDTO.swift
  Acha/Acha/Data/RecordDTO.swift
  Acha/Acha/Data/Repository/DefaultBadgeRepository.swift
  Acha/Acha/Data/Repository/DefaultRecordRepository.swift
  Acha/Acha/Data/Repository/Protocol/BadgeRepository.swift
  Acha/Acha/Data/UserDTO.swift
  Acha/Acha/Domain/Entity/Auth/SignUpData.swift
  Acha/Acha/Domain/Entity/Badge.swift
  Acha/Acha/Domain/UseCase/DefaultMyPageUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MyPageUseCase.swift
  Acha/Acha/Presentation/Auth/Coordinator/LoginCoordinator.swift
  Acha/Acha/Presentation/Base/MapBase/MapBaseViewController.swift
  Acha/Acha/Presentation/Base/MapBase/MapBaseViewModel.swift
  Acha/Acha/Presentation/TabBar/Coordinator/MyPageCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/TabBarCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/View/SelectMapRankingHeaderView.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/View/SelectMapRecordCell.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/ViewController/SelectMapViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/ViewModel/SelectMapViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/View/GameOverView.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewController/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewModel/SingleGameViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/MyPageViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/View/BadgeCell.swift
  Acha/Acha/Presentation/TabBar/MyPage/View/MyPageHeaderView.swift
  Acha/Acha/Presentation/TabBar/MyPage/View/SettingCell.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/BadgeViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/MyInfoEditViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/MyPageViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/BadgeViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/MyPageViewModel.swift
  Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainCell.swift
  Acha/Acha/Util/Constants/ImageConstants.swift
  Acha/Acha/Util/Enums/Errors.swift
  Acha/Acha/Util/Enums/FirebaseRealtimeType.swift
  Acha/Acha/Util/Enums/SystemImageNameSpace.swift
  Acha/Acha/Util/Extension/UIFont+.swift
  Acha/Acha/Util/Extension/UIImage+.swift
  AchaLibrary/.swiftpm/xcode/xcshareddata/xcschemes/AchaLibrary.xcscheme
Labels: feature, design

#119 [게임 - 같이하기] GameRoomRepository
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Data/Repository/DefaultGameRoomRepository.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Data/Repository/Protocol/GameRoomRepository.swift
  Acha/Acha/Util/Manager/DIContainerManager.swift
  Acha/Acha/Util/Service/DefaultRandomService.swift
  Acha/Acha/Util/Service/DefaultRealtimeDatabaseNetworkService.swift
  Acha/Acha/Util/Service/Protocol/RandomService.swift
  Acha/Acha/Util/Service/Protocol/RealtimeDatabaseNetworkService.swift
Labels: ⚙️ feature

#136 [마이페이지] 뱃지+임시 이미지 캐시
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Domain/UseCase/DefaultMapBaseUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultMyPageUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MyPageUseCase.swift
  Acha/Acha/Presentation/TabBar/Coordinator/MyPageCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewController/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/View/BadgeCell.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/BadgeViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/MyPageViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/BadgeViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/MyPageViewModel.swift
  Acha/Acha/Util/Extension/UIImageView+.swift
  Acha/Acha/Util/Service/DefaultImageService.swift
Labels: ⚙️ feature

#137 [게임 - 같이하기 ] 상대 위치 보여주기
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Assets.xcassets/annotationImages/Contents.json
  Acha/Acha/Assets.xcassets/annotationImages/firstAnnotation.imageset/Contents.json
  Acha/Acha/Assets.xcassets/annotationImages/firstAnnotation.imageset/penguin.png
  Acha/Acha/Assets.xcassets/annotationImages/fourthAnnotation.imageset/Contents.json
  Acha/Acha/Assets.xcassets/annotationImages/fourthAnnotation.imageset/bunny.png
  Acha/Acha/Assets.xcassets/annotationImages/secondAnnotation.imageset/Contents.json
  Acha/Acha/Assets.xcassets/annotationImages/secondAnnotation.imageset/pet.png
  Acha/Acha/Assets.xcassets/annotationImages/thirdAnnotation.imageset/Contents.json
  Acha/Acha/Assets.xcassets/annotationImages/thirdAnnotation.imageset/cat.png
  Acha/Acha/Domain/UseCase/DefaultMultiGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MultiGameUseCase.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/View/PlayerAnnotation.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/View/PlayerAnnotationView.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/View/PlayerCircle.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameViewModel.swift
  Acha/Acha/Util/Extension/MKCircle+.swift
  Acha/Acha/Util/Extension/UIImage+.swift
Labels: ⚙️ feature

#142 [게임 - 같이하기] 게임 종료 및 옵저빙 오류 수정
  Acha/Acha/Domain/UseCase/DefaultMultiGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MultiGameUseCase.swift
  Acha/Acha/Presentation/TabBar/Home/HomeView/ViewController/HomeViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/View/GameRankCollectionViewCell.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameViewModel.swift
  Acha/Acha/Util/Extension/String+.swift
Labels: 🐛 bug, ⚙️ feature

#154 [공통] DIContainer 생성
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/AppDelegate.swift
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/MultiGameCoordinator.swift
  Acha/Acha/Util/Dependency/DIContainer.swift
  Acha/Acha/Util/Dependency/DependenciesContainer.swift
  Acha/Acha/Util/Dependency/DependenciesDefinition.swift
  Acha/Acha/Util/Dependency/DependencyKey.swift
Labels: ⚙️ feature

#153 [게임 - 혼자하기] 유저 정보에 맞게 업로드, 다운로드
  Acha/Acha/Data/Repository/DefaultRecordRepository.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Data/Repository/Protocol/RecordRepository.swift
  Acha/Acha/Data/Repository/Protocol/UserRepository.swift
  Acha/Acha/Domain/UseCase/DefaultInGameUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultSingleGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/InGameUseCase.swift
  Acha/Acha/Presentation/TabBar/Coordinator/SingleGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRanking/InGameRankingViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewModel.swift
Labels: 🔨 refactor

#159 [핫픽스] Dicontainer 적용한 Badge
  Acha/Acha/Domain/UseCase/DefaultSingleGameUseCase.swift
  Acha/Acha/Util/Dependency/DependenciesDefinition.swift
  Acha/Acha/Util/Service/DefaultLocationService.swift
Labels: 🐛 bug

#158 [게임 - 같이하기] 실시간 채팅기능 추가
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/App/Coordinator/AppCoordinator.swift
  Acha/Acha/Data/DTO/ChatDTO.swift
  Acha/Acha/Data/DTO/RoomDTO.swift
  Acha/Acha/Data/Repository/DefaultGameRoomRepository.swift
  Acha/Acha/Data/Repository/Protocol/GameRoomRepository.swift
  Acha/Acha/Domain/Entity/Chat.swift
  Acha/Acha/Domain/UseCase/DefaultMultiGameChatUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultMultiGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MultiGameChatUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MultiGameUseCase.swift
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/MultiGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/HomeView/ViewModel/HomeViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/View/ChatCell.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameChatViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameRoomViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameChatViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameRoomViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameViewModel.swift
  Acha/Acha/Util/Extension/UIApplication+Rx.swift
  Acha/Acha/Util/Manager/DIContainerManager.swift
  Acha/Acha/Util/Service/DefaultRealtimeDatabaseNetworkService.swift
Labels: ⚙️ feature

#160 [인증] 화면 크러시 및 코디네이터 변경 및 전환 애니메이션
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Presentation/Auth/Common/ScrollAbleViewController.swift
  Acha/Acha/Presentation/Auth/Coordinator/AuthCoordinator.swift
  Acha/Acha/Presentation/Auth/Coordinator/LoginCoordinator.swift
  Acha/Acha/Presentation/Auth/Coordinator/SignupCoordinator .swift
  Acha/Acha/Presentation/Auth/ViewController/LoginViewController.swift
  Acha/Acha/Presentation/Auth/ViewController/SignupViewController.swift
Labels: 🐛 bug

#161 [인증] 인디케이터 적용, 로그인, 회원가입 리팩토링
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Data/DTO/UserDTO.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Data/Repository/LogInRepository.swift
  Acha/Acha/Data/Repository/SignUpRepository.swift
  Acha/Acha/Domain/Entity/SignUpData.swift
  Acha/Acha/Domain/UseCase/DefatulSignUpUsecase.swift
  Acha/Acha/Domain/UseCase/DefaultLoginUsecase.swift
  Acha/Acha/Domain/UseCase/Protocol/LoginUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/SignUpUseCase.swift
  Acha/Acha/Presentation/Auth/Coordinator/AuthCoordinator.swift
  Acha/Acha/Presentation/Auth/Coordinator/LoginCoordinator.swift
  Acha/Acha/Presentation/Auth/Coordinator/SignupCoordinator .swift
  Acha/Acha/Presentation/Auth/ViewModel/LoginViewModel.swift
  Acha/Acha/Presentation/Auth/ViewModel/SignUpViewModel.swift
  Acha/Acha/Util/Extension/Reactive/Rx+IndicatorAnimation.swift
  Acha/Acha/Util/Provider/AuthProvider.swift
  Acha/Acha/Util/Service/DefaultAuthService.swift
Labels: ⚙️ feature, 🔨 refactor

#162 [게임 - 혼자하기] 뱃지 획득
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Data/Repository/DefaultBadgeRepository.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Domain/UseCase/DefaultSingleGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/SingleGameUseCase.swift
  Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityDetailViewController.swift
  Acha/Acha/Presentation/TabBar/Coordinator/SingleGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewController/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewModel/SingleGameViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/BadgeViewController.swift
Labels: ⚙️ feature

#163 [마이페이지] 내 정보 수정 UI & 기능
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Data/DTO/UserDTO.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Data/Repository/Protocol/UserRepository.swift
  Acha/Acha/Domain/Entity/User.swift
  Acha/Acha/Domain/UseCase/DefaultMapBaseUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultMyInfoEditUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultMyPageUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultSelectMapUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultSingleGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MapBaseUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MyInfoEditUseCase.swift
  Acha/Acha/Presentation/Base/MapBase/MapBaseViewController.swift
  Acha/Acha/Presentation/Base/MapBase/MapBaseViewModel.swift
  Acha/Acha/Presentation/TabBar/Coordinator/MyPageCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/SingleGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/HomeView/ViewController/QRReaderViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/ViewController/SelectMapViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewController/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/ViewModel/SingleGameViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/View/BadgeCell.swift
  Acha/Acha/Presentation/TabBar/MyPage/View/InfoTextFieldView.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/CharacterSelectViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/MyInfoEditViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewController/MyPageViewController.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/CharacterSelectViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/MyInfoEditViewModel.swift
  Acha/Acha/Presentation/TabBar/MyPage/ViewModel/MyPageViewModel.swift
  Acha/Acha/Util/Dependency/DependenciesDefinition.swift
  Acha/Acha/Util/Enums/PinCharacter.swift
  Acha/Acha/Util/Extension/Collection+.swift
  Acha/Acha/Util/Extension/UITextField+.swift
  Acha/Acha/Util/Extension/UIViewController+.swift
  Acha/Acha/Util/Service/DefaultAuthService.swift
  Acha/Acha/Util/Service/DefaultLocationService.swift
  Acha/Acha/Util/Service/DefaultRealtimeDatabaseNetworkService.swift
  Acha/Acha/Util/Service/Protocol/AuthService.swift
  Acha/Acha/Util/Service/Protocol/RealtimeDatabaseNetworkService.swift
Labels: ⚙️ feature, 🎨 design

#176 [게임 - 같이하기] 채팅 키보드 적용, 시작시 현재 위치 팔로잉, 앱 종료시 방 나가기
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/App/Coordinator/AppCoordinator.swift
  Acha/Acha/AppDelegate.swift
  Acha/Acha/Data/Repository/DefaultGameRoomRepository.swift
  Acha/Acha/Data/Repository/DefaultLocationRepository.swift
  Acha/Acha/Data/Repository/DefaultUserRepository.swift
  Acha/Acha/Domain/UseCase/DefaultMultiGameUseCase.swift
  Acha/Acha/Domain/UseCase/Protocol/MultiGameUseCase.swift
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/MultiGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameChatViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameRoomViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameChatViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameRoomViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameViewModel.swift
  Acha/Acha/Util/Dependency/DependenciesDefinition.swift
  Acha/Acha/Util/Network/FBRealTimeDBType.swift
  Acha/Acha/Util/Service/DefaultLocationService.swift
  Acha/Acha/Util/Service/DefaultRealtimeDatabaseNetworkService.swift
  Acha/Acha/Util/Service/Protocol/RealtimeDatabaseNetworkService.swift
Labels: 🐛 bug, ⚙️ feature

#179 [게임 같이하기] 게임 종료 후 두 사람의 데이터만 가져오는 오류 수정, 채팅 잘 안 가는 오류 수정
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewController/MultiGameChatViewController.swift
  Acha/Acha/Presentation/TabBar/Home/MultiGame/ViewModel/MultiGameViewModel.swift
Labels: 🐛 bug
