Repository boostcampwm-2022/iOS08_Acha, pull requests merged in 2022-11, with the labels that each got.

#43 [게임 - 혼자하기] 게임 종료 UI PR #15
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Assets.xcassets/PointDarkColor.colorset/Contents.json
  Acha/Acha/Assets.xcassets/PointLightColor.colorset/Contents.json
  Acha/Acha/Presentation/TabBar/Home/GameOverViewController.swift
  Acha/Acha/Util/Extension/UIColor+.swift
  Acha/Acha/Util/Extension/UIFont+.swift
Labels: 리뷰요청

#47 [게임 혼자하기] 게임 화면 UI #32
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Assets.xcassets/BackGroundColor.colorset/Contents.json
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/GamePlayMenuView.swift
  Acha/Acha/Presentation/TabBar/Home/RecordAndsTimeBar/DistanceAndTimeBar.swift
  Acha/Acha/Presentation/TabBar/Home/RecordAndsTimeBar/PaddingLabel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGamePlayViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGamePlayViewModel.swift
  Acha/Acha/Util/Constants/ColorConstants.swift
  Acha/Acha/Util/Constants/FontConstants.swift
  Acha/Acha/Util/Constants/ImageConstants.swift
  Acha/Acha/Util/Extensions/CALayer+Extension.swift
Labels: 리뷰요청

#57 [지도] 백그라운드에서 사용자 위치 update 허용, 위치 접근 권한 거부 시 처리
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Info.plist
  Acha/Acha/Presentation/Base/MapBaseViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewController.swift
Labels: feature

#53 [게임 - 공통] 게임 중 랭킹 UI #13
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Assets.xcassets/RankingImage/Contents.json
  Acha/Acha/Assets.xcassets/RankingImage/rank0.imageset/Contents.json
  Acha/Acha/Assets.xcassets/RankingImage/rank0.imageset/medal.png
  Acha/Acha/Assets.xcassets/RankingImage/rank1.imageset/Contents.json
  Acha/Acha/Assets.xcassets/RankingImage/rank1.imageset/medal (1).png
  Acha/Acha/Assets.xcassets/RankingImage/rank2.imageset/Contents.json
  Acha/Acha/Assets.xcassets/RankingImage/rank2.imageset/medal (2).png
  Acha/Acha/Presentation/Base/MapBaseViewController.swift
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/HomeViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameMenusCell/InGameMenuCollectionViewCell.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameMenusParentViewController/InGamePlayMenuViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRanking/InGameRankingViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/Protocol/InGameMenuModelProtocol.swift
  Acha/Acha/Presentation/TabBar/Home/RecordAndsTimeBar/DistanceAndTimeBar.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGamePlayViewController.swift
  Acha/Acha/Util/Constants/FontConstants.swift
  Acha/Acha/Util/Extensions/Date+Extension.swift
  Acha/Acha/Util/Extensions/Int+Extension.swift
Labels: 리뷰요청

#63 [구역선택] RecordCollectionView 구현, RecordCollectionView에 데이터 바인딩
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Domain/Entity/Record.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapRecordCell.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewModel.swift
  Acha/Acha/Presentation/TabBar/Record/RecordCell.swift
  Acha/Acha/Presentation/TabBar/Record/RecordViewController.swift
  Acha/Acha/Presentation/TabBar/Record/RecordViewModel.swift
Labels: 리뷰요청

#64 [게임 - 혼자하기] 땅 선택 화면에 back 버튼 추가, 땅에 가까이 위치해야 시작 가능, 보고있는 화면 내 땅만 표시
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Domain/Entity/Coordinate.swift
  Acha/Acha/Domain/Entity/Map.swift
  Acha/Acha/Domain/Entity/MapRegion.swift
  Acha/Acha/Presentation/Base/MapBaseViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewModel.swift
  Acha/Acha/Util/Enums/SystemImageNameSpace.swift
Labels: feature

#68 [인증] 회원가입 기능
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/App/Coordinator/AppCoordinator.swift
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/Contents.json
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/email.imageset/Contents.json
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/email.imageset/email.png
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/invalidate.imageset/Contents.json
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/invalidate.imageset/exclamation-mark.png
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/nickname.imageset/Contents.json
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/nickname.imageset/name.png
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/password.imageset/Contents.json
  Acha/Acha/Assets.xcassets/AuthTextFieldImageSets/password.imageset/padlock.png
  Acha/Acha/Data/BadgeDTO.swift
  Acha/Acha/Data/RecordDTO.swift
  Acha/Acha/Data/UserDTO.swift
  Acha/Acha/Domain/Entity/Auth/SignUpData.swift
  Acha/Acha/Presentation/Auth/AuthButton/AuthButton.swift
  Acha/Acha/Presentation/Auth/AuthInputTextField/AuthInputTextField.swift
  Acha/Acha/Presentation/Auth/AuthTitleView/AuthTitleView.swift
  Acha/Acha/Presentation/Auth/Coordinator/SignupCoordinator .swift
  Acha/Acha/Presentation/Auth/Login/LoginViewController.swift
  Acha/Acha/Presentation/Auth/Login/ViewModel/LoginViewModel.swift
  Acha/Acha/Presentation/Auth/Repositories/AuthRepository.swift
  Acha/Acha/Presentation/Auth/ScrollAbleViewController/ScrollAbleViewController.swift
  Acha/Acha/Presentation/Auth/Signup/SignupViewController.swift
  Acha/Acha/Presentation/Auth/Signup/ViewModel/SignUpViewModel.swift
  Acha/Acha/Presentation/Auth/UseCase/AuthUseCase.swift
  Acha/Acha/SceneDelegate.swift
  Acha/Acha/Util/Constants/ImageConstants.swift
  Acha/Acha/Util/Extension/Encodable+Extension.swift
  Acha/Acha/Util/Extension/String+Extension.swift
  Acha/Acha/Util/Extension/UIImage+Extension.swift
  Acha/Acha/Util/Extension/UITextField+Extension.swift
  Acha/Acha/Util/KeyboardManager/KeyboardManager.swift
Labels: 리뷰요청

#69 [게임 - 혼자하기] 게임 완료 PR #33
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Domain/Entity/Map.swift
  Acha/Acha/Domain/Entity/Record.swift
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/SingleGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRanking/InGameRankingViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRanking/InGameRankingViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/GameOverViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/GameOverViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/SingleGameViewModel.swift
  Acha/Acha/Presentation/TabBar/Record/RecordViewModel.swift
  Acha/Acha/Util/Extension/String+.swift
  Acha/Acha/Util/Extension/UIViewController+.swift
  Acha/WorkSpace by 25km:h.gpx
  Acha/WorkSpace by 6km:h.gpx
Labels: 리뷰요청

#77 [게임 - 혼자하기] 🚨 오류 제거, 알랏 추가 🚨 PR
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/GameOverViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/GameOverViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/SingleGameViewModel.swift
  Acha/Acha/Util/Extension/UIViewController+.swift
  Acha/국민대 12KMH.gpx
  Acha/국민대 30KMH.gpx
  Acha/부원여중 12KMH.gpx
  Acha/부원여중 5MPH.gpx
  Acha/부평동초등학교 4.2MPH.gpx
  Acha/부평동초등학교 4MPH.gpx
  Acha/부평동초등학교 5MPH.gpx
Labels: 리뷰요청

#84 [게임 - 혼자하기] 클린 PR
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/App/Coordinator/AppCoordinator.swift
  Acha/Acha/Data/RecordDTO.swift
  Acha/Acha/Data/Repository/DefaultRecordRepository.swift
  Acha/Acha/Data/Repository/Protocol/RecordRepository.swift
  Acha/Acha/Domain/Entity/Map.swift
  Acha/Acha/Domain/Entity/Record.swift
  Acha/Acha/Domain/UseCase/DefaultInGameUseCase.swift
  Acha/Acha/Domain/UseCase/DefaultSingleGameUseCase.swift
  Acha/Acha/Domain/UseCase/InGameUseCase.swift
  Acha/Acha/Domain/UseCase/SingleGameUseCase.swift
  Acha/Acha/Presentation/Base/MapBaseViewController.swift
  Acha/Acha/Presentation/TabBar/Coordinator/HomeCoordinator.swift
  Acha/Acha/Presentation/TabBar/Coordinator/SingleGameCoordinator.swift
  Acha/Acha/Presentation/TabBar/Home/HomeViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRanking/InGameRankingViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRanking/InGameRankingViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewController.swift
  Acha/Acha/Presentation/TabBar/Home/InGameMenus/InGameRecord/InGameRecordViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SelectMap/SelectMapViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/GameOverView.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/GameOverViewModel.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/SingleGameViewController.swift
  Acha/Acha/Presentation/TabBar/Home/SingleGame/SingleGameViewModel.swift
  Acha/Acha/Util/Enums/Errors.swift
  Acha/Acha/Util/Enums/FirebasePath.swift
  Acha/Acha/Util/Extension/CLLocationCoordinate2D+.swift
  Acha/Acha/Util/Service/DefaultLocationService.swift
  Acha/Acha/Util/Service/DefaultRealtimeDatabaseNetworkService.swift
  Acha/Acha/Util/Service/LocationService.swift
  Acha/Acha/Util/Service/RealtimeDatabaseNetworkService.swift
  Acha/Acha/Util/Service/TimerService.swift
  Acha/Acha/Util/Service/TimerServiceProtocol.swift
Labels: 리뷰요청

#88 [커뮤니티] 홈, 글 쓰기, 디테일 UI
  Acha/Acha.xcodeproj/project.pbxproj
  Acha/Acha/Assets.xcassets/CommentBoxColor.colorset/Contents.json
  Acha/Acha/Assets.xcassets/commentImage.imageset/Contents.json
  Acha/Acha/Assets.xcassets/commentImage.imageset/bubble 1.png
  Acha/Acha/Assets.xcassets/defaultSelectImage.imageset/Contents.json
  Acha/Acha/Assets.xcassets/defaultSelectImage.imageset/이미지 추가.png
  Acha/Acha/Data/CommentDTO.swift
  Acha/Acha/Data/CommunityDTO.swift
  Acha/Acha/Data/PostDTO.swift
  Acha/Acha/Domain/Entity/Comment.swift
  Acha/Acha/Domain/Entity/Post.swift
  Acha/Acha/Presentation/TabBar/Community/Cell/CommentCollectionViewCell.swift
  Acha/Acha/Presentation/TabBar/Community/Cell/CommentHeaderCollectionReusableView.swift
  Acha/Acha/Presentation/TabBar/Community/Cell/CommunityCollectionViewCell.swift
  Acha/Acha/Presentation/TabBar/Community/Cell/PostCollectionViewCell.swift
  Acha/Acha/Presentation/TabBar/Community/Cell/PostHeaderCollectionReusableView.swift
  Acha/Acha/Presentation/TabBar/Community/Common/CommentView.swift
  Acha/Acha/Presentation/TabBar/Community/Common/TextCountView.swift
  Acha/Acha/Presentation/TabBar/Community/CommunityViewController.swift
  Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityDetailViewController.swift
  Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityPostViewController.swift
  Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityViewController.swift
  Acha/Acha/Presentation/TabBar/Coordinator/CommunityCoordinator.swift
  Acha/Acha/Presentation/TabBar/Record/RecordViewController.swift
  Acha/Acha/Util/Extension/UIColor+.swift
  Acha/Acha/Util/Extension/UIImage+Extension.swift
  Acha/Acha/Util/KeyboardManager/KeyboardManager.swift
Labels: design
